### ISSUE TITLE
Failing for some currencies

### ISSUE THREAD

**Issue by praveendath92** [heyajohnny/cryptoinfo#6]
It's working fine for BTC and ETH but failing for some other currencies. See logs

Logger: homeassistant.helpers.entity
Source: custom_components/cryptoinfo/sensor.py:87
First occurred: 4:52:17 PM (45 occurrences)
Last logged: 4:56:21 PM

Update for sensor.cryptoinfo_cel_usd fails
Update for sensor.cryptoinfo_xrp_usd fails
Update for sensor.cryptoinfo_dot_usd fails
Update for sensor.cryptoinfo_yfi_usd fails
Update for sensor.cryptoinfo_matic_usd fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 471, in async_device_update
    await self.hass.async_add_executor_job(self.update)  # type: ignore
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/cryptoinfo/sensor.py", line 129, in _update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/cryptoinfo/sensor.py", line 87, in _update
    value = r.json()[self.cryptocurrency_name][self.currency_name]
KeyError: 'cel'

**Comment by heyajohnny** [comment]
You are probably using the "symbol" value as "cryptocurrency_name". 
You need to use the "id" value for "cryptocurrency_name".

Try these values for "cryptocurrency_name":
- "celsius-degree-token"
- "ripple"
- "polkadot"
- "yearn-finance"
- "matic-network"

And please let me know if it solves your issue ;)

**Comment by praveendath92** [comment]
That worked! Thanks @heyajohnny 🥇

**Comment by HGabet** [comment]
Thanks a lot !
